name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  release-please-action:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@main
        id: release-action
        with:
          release-type: node
    outputs:
      is-release-created: ${{ steps.release-action.outputs.releases_created }}

  build:
    needs: [release-please-action]
    if: ${{ needs.release-please-action.outputs.is-release-created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install, build, and upload your site
        uses: withastro/action@main
        with:
          node-version: '21.x'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
