name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@main
        with:
          node-version: '20.x'

  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@main
        with:
          release-type: node

  deploy:
    needs: release-please
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
