name: Deploy to GitHub Pages...

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@main
      - name: Install, build, and upload your site
        uses: withastro/action@main
        with:
          node-version: '20.x'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.head_commit.message, 'chore(main): release') }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
